version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...

  pre_build:
    commands:
      - echo Entered the pre_build phase...

  build:
    commands:
      - echo Entered the build phase...
      - gradle bootRepackage test

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/calmeter-0.0.1.jar
  discard-paths: yes
