version: 0.1

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...

  pre_build:
    commands:
      - echo Entered the pre_build phase...

  build:
    commands:
      - echo Entered the build phase...
      - gradle bootRepackage test

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`